name: Waka Reame

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          LOCALE: fr_FR
          SHOW_UPDATED_DATE: true
          SHOW_LINES_OF_CODE: true
          SHOW_TOTAL_CODE_TIME: true
          SHOW_PROFILE_VIEWS: true
          SHOW_LANGUAGE: true
          SHOW_OS: true
          SHOW_TIMEZONE: true
          SHOW_EDITORS: true
          SHOW_SHORT_INFO: true
